import { useMutation, useQueryClient } from '@tanstack/react-query';
import { router } from 'expo-router';
import { useState } from 'react';
import { Alert, ScrollView, StyleSheet, Text } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Button, colors, Field } from '@/components/ui';
import { apiErrorMessage } from '@/config/api';
import { createGig } from '@/lib/gig-api';
import { useAuth } from '@/providers/auth-provider';
export default function PostGigScreen() { const { token } = useAuth(); const client = useQueryClient(); const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [skills, setSkills] = useState(''); const [budget, setBudget] = useState(''); const [deadline, setDeadline] = useState(''); const [location, setLocation] = useState(''); const mutation = useMutation({ mutationFn: () => createGig(token!, { title, description, skillsRequired: skills.split(',').map((item) => item.trim()).filter(Boolean), budget: Number(budget), deadline, location }), onSuccess: (gig) => { client.invalidateQueries({ queryKey: ['my-gigs'] }); client.invalidateQueries({ queryKey: ['gigs'] }); router.replace(`/(business)/gig/${gig.id}` as never); }, onError: (e) => Alert.alert('Could not post gig', apiErrorMessage(e)) }); return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Text style={s.heading}>Post a gig</Text><Field label="Title" value={title} onChangeText={setTitle} placeholder="What do you need done?" /><Field label="Description" value={description} onChangeText={setDescription} multiline /><Field label="Skills required" value={skills} onChangeText={setSkills} placeholder="Design, Excel, writing" /><Field label="Budget (₹)" value={budget} onChangeText={setBudget} keyboardType="decimal-pad" /><Field label="Deadline" value={deadline} onChangeText={setDeadline} placeholder="2026-09-15T17:00:00.000Z" /><Field label="Location" value={location} onChangeText={setLocation} placeholder="Simple text location" /><Button title={mutation.isPending ? 'Posting…' : 'Post gig'} disabled={mutation.isPending} onPress={() => mutation.mutate()} /></ScrollView></SafeAreaView>; }
const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.pale }, content: { padding: 20, gap: 15 }, heading: { color: colors.navy, fontSize: 28, fontWeight: '800' } });
