import { useQuery } from '@tanstack/react-query';
import { router } from 'expo-router';
import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { colors, Field } from '@/components/ui';
import { apiErrorMessage } from '@/config/api';
import { listGigs } from '@/lib/gig-api';
import { useAuth } from '@/providers/auth-provider';

export default function FeedScreen() { const { token } = useAuth(); const [skill, setSkill] = useState(''); const [minBudget, setMinBudget] = useState(''); const [maxBudget, setMaxBudget] = useState(''); const query = useQuery({ queryKey: ['gigs', skill, minBudget, maxBudget], queryFn: () => listGigs(token!, { ...(skill ? { skill } : {}), ...(minBudget ? { minBudget } : {}), ...(maxBudget ? { maxBudget } : {}) }), enabled: !!token }); return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Text style={s.heading}>Find a gig</Text><View style={s.filters}><Field label="Skill" value={skill} onChangeText={setSkill} placeholder="e.g. Design" /><View style={s.range}><View style={s.half}><Field label="Min budget" value={minBudget} onChangeText={setMinBudget} keyboardType="decimal-pad" /></View><View style={s.half}><Field label="Max budget" value={maxBudget} onChangeText={setMaxBudget} keyboardType="decimal-pad" /></View></View></View>{query.isError && <Text style={s.error}>{apiErrorMessage(query.error)}</Text>}{query.data?.map((gig) => <Pressable key={gig.id} style={s.card} onPress={() => router.push(`/(student)/gig/${gig.id}` as never)}><View style={s.cardTop}><Text style={s.title}>{gig.title}</Text><Text style={s.budget}>₹{Number(gig.budget).toLocaleString()}</Text></View><Text style={s.copy} numberOfLines={2}>{gig.description}</Text><Text style={s.meta}>Due {new Date(gig.deadline).toLocaleDateString()} · {gig.location}</Text><View style={s.chips}>{gig.skillsRequired.map((item) => <Text style={s.chip} key={item}>{item}</Text>)}</View></Pressable>)}{query.data?.length === 0 && <Text style={s.copy}>No open gigs match these filters.</Text>}</ScrollView></SafeAreaView>; }
const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.pale }, content: { padding: 20, gap: 14 }, heading: { fontSize: 28, fontWeight: '800', color: colors.navy }, filters: { backgroundColor: colors.white, padding: 14, borderRadius: 14, gap: 6 }, range: { flexDirection: 'row', gap: 10 }, half: { flex: 1 }, card: { backgroundColor: colors.white, borderRadius: 14, padding: 16, gap: 9 }, cardTop: { flexDirection: 'row', justifyContent: 'space-between', gap: 10 }, title: { color: colors.navy, fontSize: 18, fontWeight: '800', flex: 1 }, budget: { color: colors.blue, fontWeight: '800' }, copy: { color: colors.muted, lineHeight: 20 }, meta: { color: colors.text, fontSize: 12 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 }, chip: { backgroundColor: colors.pale, color: colors.blue, fontWeight: '700', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 10, fontSize: 12 }, error: { color: colors.danger } });
