import * as ImagePicker from 'expo-image-picker';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { router } from 'expo-router';
import { useEffect, useState } from 'react';
import { Alert, Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Button, colors, Field, ImagePreview, VerificationBadge } from '@/components/ui';
import { apiErrorMessage } from '@/config/api';
import { addPortfolioItem, getProfile, removePortfolioItem, updateProfile, uploadImage } from '@/lib/profile-api';
import { useAuth } from '@/providers/auth-provider';
import { Availability, StudentProfile } from '@/types/api';

const availabilityLabels: Record<Availability, string> = { FULL_TIME_AVAILABLE: 'Full time', PART_TIME: 'Part time', WEEKENDS_ONLY: 'Weekends only' };

export default function StudentProfileScreen() {
  const { token } = useAuth(); const client = useQueryClient();
  const profileQuery = useQuery({ queryKey: ['profile'], queryFn: () => getProfile(token!), enabled: !!token });
  const profile = profileQuery.data?.profile as StudentProfile | null | undefined;
  const [college, setCollege] = useState(''); const [skills, setSkills] = useState(''); const [bio, setBio] = useState(''); const [availability, setAvailability] = useState<Availability>('PART_TIME'); const [photoUrl, setPhotoUrl] = useState<string | null>(null); const [portfolioTitle, setPortfolioTitle] = useState(''); const [portfolioImageUrl, setPortfolioImageUrl] = useState<string | null>(null);
  useEffect(() => { if (profile) { setCollege(profile.college); setSkills(profile.skills.join(', ')); setBio(profile.bio); setAvailability(profile.availability); setPhotoUrl(profile.profileImageUrl); } }, [profile]);
  const refresh = () => client.invalidateQueries({ queryKey: ['profile'] });
  const save = useMutation({ mutationFn: () => updateProfile(token!, { college, skills: skills.split(',').map((x) => x.trim()).filter(Boolean), bio, availability, profileImageUrl: photoUrl }), onSuccess: refresh, onError: (e) => Alert.alert('Could not save profile', apiErrorMessage(e)) });
  const addItem = useMutation({ mutationFn: () => addPortfolioItem(token!, { title: portfolioTitle, imageUrl: portfolioImageUrl }), onSuccess: () => { setPortfolioTitle(''); setPortfolioImageUrl(null); refresh(); }, onError: (e) => Alert.alert('Could not add portfolio item', apiErrorMessage(e)) });
  const removeItem = useMutation({ mutationFn: (id: string) => removePortfolioItem(token!, id), onSuccess: refresh, onError: (e) => Alert.alert('Could not remove item', apiErrorMessage(e)) });
  async function pickImage(target: 'profile' | 'portfolio', camera = false) {
    const permission = camera ? await ImagePicker.requestCameraPermissionsAsync() : await ImagePicker.requestMediaLibraryPermissionsAsync();
    if (!permission.granted) return Alert.alert('Permission needed', 'Allow photo access to upload an image.');
    const result = camera ? await ImagePicker.launchCameraAsync({ mediaTypes: ['images'], quality: 0.8 }) : await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], quality: 0.8 });
    if (result.canceled) return;
    try { const url = await uploadImage(token!, result.assets[0]); target === 'profile' ? setPhotoUrl(url) : setPortfolioImageUrl(url); } catch (e) { Alert.alert('Upload failed', apiErrorMessage(e)); }
  }
  function chooseImage(target: 'profile' | 'portfolio') { Alert.alert('Add image', 'Choose a source', [{ text: 'Camera', onPress: () => void pickImage(target, true) }, { text: 'Photo library', onPress: () => void pickImage(target) }, { text: 'Cancel', style: 'cancel' }]); }
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><View style={styles.top}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹ Back</Text></Pressable><Text style={styles.heading}>Student profile</Text><VerificationBadge verified={profile?.isVerified ?? false} /></View><View style={styles.section}><ImagePreview uri={photoUrl} label="Profile photo" /><Button title="Choose profile photo" variant="outline" onPress={() => chooseImage('profile')} /></View><View style={styles.form}><Field label="College" value={college} onChangeText={setCollege} placeholder="Your college" /><Field label="Skills" value={skills} onChangeText={setSkills} placeholder="Design, Excel, tutoring" /><Field label="About you" value={bio} onChangeText={setBio} multiline placeholder="A short introduction" /><Text style={styles.label}>Availability</Text><View style={styles.choices}>{(Object.keys(availabilityLabels) as Availability[]).map((value) => <Pressable key={value} onPress={() => setAvailability(value)} style={[styles.choice, availability === value && styles.choiceSelected]}><Text style={[styles.choiceText, availability === value && styles.choiceTextSelected]}>{availabilityLabels[value]}</Text></Pressable>)}</View><Button title={save.isPending ? 'Saving…' : 'Save profile'} disabled={save.isPending} onPress={() => save.mutate()} /></View><View style={styles.portfolio}><Text style={styles.sectionTitle}>Portfolio</Text><Field label="Project title" value={portfolioTitle} onChangeText={setPortfolioTitle} placeholder="e.g. Cafe menu design" /><ImagePreview uri={portfolioImageUrl} label="Portfolio image" /><Button title="Choose portfolio image" variant="outline" onPress={() => chooseImage('portfolio')} /><Button title={addItem.isPending ? 'Adding…' : 'Add portfolio item'} disabled={!portfolioTitle.trim() || addItem.isPending} onPress={() => addItem.mutate()} /><View style={styles.grid}>{profile?.portfolioItems.map((item) => <View key={item.id} style={styles.item}>{item.imageUrl ? <Image source={{ uri: item.imageUrl }} style={styles.itemImage} /> : <View style={styles.itemImage} />}<Text style={styles.itemTitle}>{item.title}</Text><Pressable onPress={() => removeItem.mutate(item.id)}><Text style={styles.delete}>Remove</Text></Pressable></View>)}</View></View></ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.pale }, content: { padding: 20, gap: 20 }, top: { gap: 10 }, back: { color: colors.blue, fontWeight: '700' }, heading: { fontSize: 28, color: colors.navy, fontWeight: '800' }, section: { backgroundColor: colors.white, borderRadius: 14, padding: 16, gap: 12, alignItems: 'flex-start' }, form: { backgroundColor: colors.white, borderRadius: 14, padding: 16, gap: 15 }, label: { fontWeight: '700', color: colors.text }, choices: { gap: 8 }, choice: { borderWidth: 1, borderColor: colors.border, borderRadius: 8, padding: 10 }, choiceSelected: { borderColor: colors.blue, backgroundColor: colors.pale }, choiceText: { color: colors.muted }, choiceTextSelected: { color: colors.blue, fontWeight: '700' }, portfolio: { backgroundColor: colors.white, borderRadius: 14, padding: 16, gap: 14 }, sectionTitle: { fontSize: 21, color: colors.navy, fontWeight: '800' }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, item: { width: '47%', borderWidth: 1, borderColor: colors.border, borderRadius: 10, padding: 8, gap: 6 }, itemImage: { width: '100%', aspectRatio: 1, backgroundColor: colors.pale, borderRadius: 6 }, itemTitle: { color: colors.text, fontWeight: '700' }, delete: { color: colors.danger, fontWeight: '700' } });
