import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useLocalSearchParams } from 'expo-router';
import { Alert, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Button, colors } from '@/components/ui';
import { apiErrorMessage } from '@/config/api';
import { getApplicants, rejectApplicant, selectApplicant } from '@/lib/gig-api';
import { useAuth } from '@/providers/auth-provider';
export default function ApplicantsScreen() { const { gigId } = useLocalSearchParams<{ gigId: string }>(); const { token } = useAuth(); const client = useQueryClient(); const query = useQuery({ queryKey: ['applicants', gigId], queryFn: () => getApplicants(token!, gigId), enabled: !!token && !!gigId }); const refresh = () => { client.invalidateQueries({ queryKey: ['applicants', gigId] }); client.invalidateQueries({ queryKey: ['gig', gigId] }); client.invalidateQueries({ queryKey: ['my-gigs'] }); }; const select = useMutation({ mutationFn: selectApplicant.bind(null, token!), onSuccess: refresh, onError: (e) => Alert.alert('Could not select applicant', apiErrorMessage(e)) }); const reject = useMutation({ mutationFn: rejectApplicant.bind(null, token!), onSuccess: refresh, onError: (e) => Alert.alert('Could not reject applicant', apiErrorMessage(e)) }); return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Text style={s.heading}>Applicants</Text>{query.data?.map((application) => <View style={s.card} key={application.id}><Text style={s.name}>{application.student.name}</Text><Text style={s.copy}>{application.student.studentProfile?.skills.join(' · ') || 'No skills listed'}</Text><Text style={s.copy}>{application.proposal}</Text><Text style={s.rating}>Rating: — · Past gigs: {application.pastGigCount}</Text><Text style={s.status}>{application.status}</Text>{application.status !== 'REJECTED' && application.status !== 'SELECTED' && <View style={s.actions}><Button title="Select" onPress={() => select.mutate(application.id)} disabled={select.isPending} /><Button title="Reject" variant="outline" onPress={() => reject.mutate(application.id)} disabled={reject.isPending} /></View>}</View>)}</ScrollView></SafeAreaView>; }
const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.pale }, content: { padding: 20, gap: 12 }, heading: { color: colors.navy, fontSize: 28, fontWeight: '800' }, card: { padding: 16, borderRadius: 14, backgroundColor: colors.white, gap: 7 }, name: { color: colors.navy, fontSize: 18, fontWeight: '800' }, copy: { color: colors.text, lineHeight: 20 }, rating: { color: colors.muted }, status: { color: colors.blue, fontWeight: '800' }, actions: { gap: 8, marginTop: 5 } });
