import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { router, useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { Alert, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Button, colors, Field } from '@/components/ui';
import { StatusTracker } from '@/components/status-tracker';
import { apiErrorMessage } from '@/config/api';
import { approveGig, getGig, requestRevision } from '@/lib/gig-api';
import { useAuth } from '@/providers/auth-provider';
export default function BusinessGigScreen() { const { id } = useLocalSearchParams<{ id: string }>(); const { token } = useAuth(); const client = useQueryClient(); const [feedback, setFeedback] = useState(''); const query = useQuery({ queryKey: ['gig', id], queryFn: () => getGig(token!, id), enabled: !!token && !!id }); const refresh = () => { client.invalidateQueries({ queryKey: ['gig', id] }); client.invalidateQueries({ queryKey: ['my-gigs'] }); }; const approve = useMutation({ mutationFn: () => approveGig(token!, id), onSuccess: refresh, onError: (e) => Alert.alert('Could not approve', apiErrorMessage(e)) }); const revision = useMutation({ mutationFn: () => requestRevision(token!, id, feedback), onSuccess: refresh, onError: (e) => Alert.alert('Could not request revision', apiErrorMessage(e)) }); const gig = query.data; if (!gig) return null; return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Text style={s.heading}>{gig.title}</Text><Text style={s.budget}>₹{Number(gig.budget).toLocaleString()}</Text><StatusTracker status={gig.status} /><Text style={s.copy}>{gig.description}</Text><Text style={s.copy}>Due {new Date(gig.deadline).toLocaleDateString()} · {gig.location}</Text>{gig.status === 'OPEN' && <Button title={`View applicants (${gig.applications?.length ?? 0})`} onPress={() => router.push(`/(business)/applicants/${id}` as never)} />}{gig.status === 'SUBMITTED' && <View style={s.card}><Text style={s.section}>Review deliverable</Text><Text style={s.copy}>{gig.deliverables?.[0]?.note || 'No note provided'}</Text><Field label="Revision feedback" value={feedback} onChangeText={setFeedback} multiline /><Button title={revision.isPending ? 'Sending…' : 'Request revision'} variant="outline" disabled={!feedback || revision.isPending} onPress={() => revision.mutate()} /><Button title={approve.isPending ? 'Approving…' : 'Approve'} disabled={approve.isPending} onPress={() => approve.mutate()} /></View>}</ScrollView></SafeAreaView>; }
const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.pale }, content: { padding: 20, gap: 15 }, heading: { color: colors.navy, fontSize: 28, fontWeight: '800' }, budget: { color: colors.blue, fontSize: 20, fontWeight: '800' }, copy: { color: colors.text, lineHeight: 21 }, card: { backgroundColor: colors.white, borderRadius: 14, padding: 16, gap: 13 }, section: { color: colors.navy, fontSize: 18, fontWeight: '800' } });
